### ISSUE TITLE
Investigate UI tests in build step

### ISSUE THREAD

**Issue by nranas** [cignium/hypermedia-client#109]

**Comment by nranas** [comment]
I think we should consider using [Jest](https://facebook.github.io/jest/) for this since we are already using it for the unit tests and it is facebooks own testing framework.

**Comment by nranas** [comment]
We now have a working example of a simple UI test running in the travis build against browserstack. If we want to continue with the current setup we need to buy a browserstack account and add more tests.

**Comment by hfjallemark** [comment]
Isn't Browserstack free for OSS?

**Comment by nranas** [comment]
They have some kind of free open source plan which you have to apply for.

![image](https://cloud.githubusercontent.com/assets/1560231/25839227/0de9ca02-3497-11e7-8de0-39e7a48c8d95.png)

Not sure what would be included in that but I guess we are mostly interested in the automate parts.

**Comment by nranas** [comment]
I have sent a request to them now and are awaiting the response.

**Comment by nranas** [comment]
We now have a Browserstack account with the open source plan activated. I have sent some invites. I think that concludes this issue and I will open a new issue to extend the test suit to get more coverage.
