### ISSUE TITLE
Remove broken version/re-publish previous version

### ISSUE THREAD

**Issue by nranas** [cignium/hypermedia-client#112]
We need a way to revert to a previous version in the case where we create a broken version.

**Comment by nranas** [comment]
I think the simplest way to revert to a previous version for our users is to move the `latest` tag to the version we want to revert to. The version with the `latest` tag is the one that will be fetched for everyone including the client without specifying any particular version. When this client gets more mature and more users we might want to consider using some kind of `beta` or `next` tag for new releases to further improve stability (see blog-post linked below for more information).

- [npm dist-tag](https://docs.npmjs.com/cli/dist-tag)
- [Using npm's package distribution tags to ship stable releases](https://blog.greenkeeper.io/one-simple-trick-for-javascript-package-maintainers-to-avoid-breaking-their-user-s-software-and-to-6edf06dc5617)

**Comment by nranas** [comment]
We will need authorization in the npm account to be able to continue with this. @hfjallemark, please advise.

**Comment by hfjallemark** [comment]
Everyone who should have access to npm needs to create an account. Let me know your users names and I will add everyone as collaborators.

**Comment by nranas** [comment]
My username is [**nranas**](https://www.npmjs.com/~nranas)

//cc @robcar @magahl @Edgar-Cordova @sbochoa @Diego-T

**Comment by magahl** [comment]
My username is **[magahl](https://www.npmjs.com/~magahl)**

**Comment by robcar** [comment]
And mine is [robinc](https://www.npmjs.com/~robinc)

**Comment by hfjallemark** [comment]
Added.

**Comment by nranas** [comment]
I can confirm that this works now. To move the `latest` tag to a different version you would run the following command from the console:
`npm dist-tag add cignium-hypermedia-client@<version> latest`
where `<version>` is the version you want to set as the latest.
