### ISSUE TITLE
Filename naming policy

### ISSUE THREAD

**Issue by nolsherry** [cignium/hypermedia-client#87]
Hello @hfjallemark  ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
There is the problem need to confirm with you. 
I downloaded the repository from [npm](https://www.npmjs.com/package/cignium-hypermedia-client), 
but I found the files in `dist` folder do not follow the same naming policy. In other words, `client.min.js`, 
`default.css` do not follow the same naming policy. Maybe the files in `dist` folder can follow the same naming policy. What do you think? thanks!

cdnjs/cdnjs#9152

**Comment by hfjallemark** [comment]
That's because `default.css` represents the default theme and there may be additional themes included in future releases. Hence it wouldn't make sense with `client.css`.

++ @nranas

**Comment by nolsherry** [comment]
@hfjallemark , thanks for your response, we get it.
