### ISSUE TITLE
Some versions files problems

### ISSUE THREAD

**Issue by nolsherry** [cignium/hypermedia-client#88]
Hi, @hfjallemark ,
thanks for your response in [hypermedia-client/Issue#87](https://github.com/cignium/hypermedia-client/issues/87), and I have another problem as follows: 
I found that the structure of `v1.0.0`, `v1.0.1` and `v1.0.2` from npm are different from other versions after `v1.0.2`. It does not exist `dist` folder, which files need to be grab in those versions(`v1.0.0`/`v1.0.1`/`v1.0.2`)? Thanks!

cdnjs/cdnjs#9152

**Comment by hfjallemark** [comment]
There was no build/ci process in place in those versions so unfortunately they don't exist.

**Comment by nolsherry** [comment]
@hfjallemark , maybe we can grab `client.js` in `src` folder in those version. What do you think?

**Comment by hfjallemark** [comment]
Unfortunately that file is untranspiled ES6/7 code so will not work on a cdn, you should need a transpiler like Babel to be able to use it.

**Comment by nolsherry** [comment]
@hfjallemark , thanks for your reminding, maybe we will ignore these versions(`v1.0.0`/`v1.0.1`/`v1.0.2`)?
What do you think?

**Comment by hfjallemark** [comment]
@nolsherry sorry for not getting back sooner -- yes, let's ignore those versions.
